name: Run asan

on:
  push:

jobs:
  run-asan:
    name: '${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest]
    
    steps:
      - uses: actions/checkout@v4
      - name: compile with c
        run: |
          gcc -g -fsanitize=address -o t t.c
          while true; do ASAN_OPTIONS=sleep_before_dying=1000 ./t 2>&1 | tee -a log;done
          cat log | grep -A 1 "ERROR: AddressSanitizer"
          cat log
